### PR TITLE
cmd/dap: add dlv dap --foreground

### PR DESCRIPTION
**Pull request by polinasok**
updates #2552

### CODE REVIEW

**Comment by aarzilli** [comment]
Wouldn't it be better to just have it always pass true? Or at least have the foreground flag default to true?

**Comment by derekparker** [comment]
Should this simply be closed since https://github.com/go-delve/delve/pull/2589 was merged? The diff on this looks wrong too, it's not taking into account the PR, it seems.

**Comment by polinasok** [comment]
> Should this simply be closed since #2589 was merged? The diff on this looks wrong too, it's not taking into account the PR, it seems.

Yes, this needed a merge.

**Comment by derekparker** [comment]
@polinasok can you run `go run _scripts/gen-usage-docs.go`

**Comment by hyangah** [comment]
If this is useful for delve dap users, can this be applied to other headless commands?

**Comment by polinasok** [comment]
> If this is useful for delve dap users, can this be applied to other headless commands?

I think there isn't general consensus that this is useful, which is why I only added it to dlv dap.

**Comment by polinasok** [comment]
Any additional thoughts? Votes for or against?

**Comment by aarzilli** [comment]
Generally against, I don't see many people asking for this and it doesn't seem useful.

**Pull request closed without merging**
