### PR TITLE
proc: fix hang caused by g.atomicstatus has change to atomic.Uint32

### PR DESCRIPTION
**Pull request by cuiweixie**

### CODE REVIEW

**Comment by cuiweixie** [comment]
how can I debug the TeamCity Build failed.

**Review by aarzilli — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by yjian118** [comment]
I get an error after this commit: 
# github.com/go-delve/delve/pkg/proc
src/github.com/go-delve/delve/pkg/proc/variables.go:927:6: undefined: constant.Val
The command '/bin/sh -c go get github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2

Any idea to solve it?

**Comment by derekparker** [comment]
> I get an error after this commit:
> 
> # github.com/go-delve/delve/pkg/proc
> src/github.com/go-delve/delve/pkg/proc/variables.go:927:6: undefined: constant.Val The command '/bin/sh -c go get github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2
> 
> Any idea to solve it?

`constant.Val` is in the Go standard library, so it should be defined. Can you provide any other details about your environment / Go version / etc?

**Comment by yjian118** [comment]
> > I get an error after this commit:
> > # github.com/go-delve/delve/pkg/proc
> > src/github.com/go-delve/delve/pkg/proc/variables.go:927:6: undefined: constant.Val The command '/bin/sh -c go get github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2
> > Any idea to solve it?
> 
> `constant.Val` is in the Go standard library, so it should be defined. Can you provide any other details about your environment / Go version / etc?

Hi, I think this is because my go version is a little outdated: golang:1.12.9.
Previously, I'm trying to use "RUN go get github.com/go-delve/delve/cmd/dlv" in my docker file, I'm wondering if I need to switch to "go mod" in my dockerfile to specify the version of dlv, or if you have any suggestion?

**Comment by derekparker** [comment]
> > > I get an error after this commit:
> > > # github.com/go-delve/delve/pkg/proc
> > > src/github.com/go-delve/delve/pkg/proc/variables.go:927:6: undefined: constant.Val The command '/bin/sh -c go get github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2
> > > Any idea to solve it?
> > 
> > 
> > `constant.Val` is in the Go standard library, so it should be defined. Can you provide any other details about your environment / Go version / etc?
> 
> Hi, I think this is because my go version is a little outdated: golang:1.12.9. Previously, I'm trying to use "RUN go get github.com/go-delve/delve/cmd/dlv" in my docker file, I'm wondering if I need to switch to "go mod" in my dockerfile to specify the version of dlv, or if you have any suggestion?

Is there any reason you can't use a more modern Go version?

**Comment by yjian118** [comment]
Yes, the reason is I’m cherry-picking some commits to a historical release, and I don’t want to move that release to a newer go version regarding the efforts in testing.

I end up with the solution below in my docker file:
“RUN apt-get update && apt-get install -y git ca-certificates libgnutls30
RUN GO111MODULE=on go get ***@***.******@***.***>
”
Hope it helps any one hit this problem

**Pull request merged**
