### PR TITLE
dap: use defaultDebugBinary instead of creating binary in temp dir with temp name

### PR DESCRIPTION
**Pull request by hyangah**
This is a partial revert of PR #2660.

Some users develop in environments where execution of binaries
in temp directory is prohibited or undesirable. Moreover, the
current implementation creates binaries with random names
and that made it more difficult to set up firewall exclusion
rules. Revert it and always use the default debug output name.
(The debug binary will be created in the delve's working directory
and an editor does not have any promise on working directory
unless user specifies it through dlvCwd. So users still need to
chase them unless they set the exclusion rule purely based on
the file base name).

Fixes golang/vscode-go#1955

cc @suzmue @polinasok

### CODE REVIEW

**Comment by hyangah** [comment]
Not sure how the following test failure is related to this PR

```
------- Stdout: -------
=== RUN   TestNoDebug_AcceptNoRequestsButDisconnect
DAP server listening at: [::]:49655
2022-01-10T20:26:33+01:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
2022-01-10T20:26:33+01:00 debug layer=dap DAP server pid = 85468
Connecting to server at: [::]:49655
2022-01-10T20:26:33+01:00 debug layer=dap DAP connection 69 started
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":1,"type":"request","command":"initialize","arguments":{"adapterID":"go","locale":"en-us","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path","supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true}}
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsDelayedStackTraceLoading":true,"supportsLogPoints":true,"supportsDisassembleRequest":true,"supportsClipboardContext":true,"supportsSteppingGranularity":true,"supportsInstructionBreakpoints":true}}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":2,"type":"request","command":"launch","arguments":{"mode":"exec","noDebug":true,"program":"/Users/builduser/agent/temp/buildTmp/http_server.5e4afb1d"}}
2022-01-10T20:26:33+01:00 debug layer=dap parsed launch config: {
  "mode": "exec",
  "program": "/Users/builduser/agent/temp/buildTmp/http_server.5e4afb1d",
  "noDebug": true,
  "backend": "default",
  "stackTraceDepth": 50
}
2022-01-10T20:26:33+01:00 debug layer=dap launching binary '/Users/builduser/agent/temp/buildTmp/http_server.5e4afb1d' with config: {
  "mode": "exec",
  "program": "/Users/builduser/agent/temp/buildTmp/http_server.5e4afb1d",
  "cwd": "/Users/builduser/agent/work/3aca8f960d346a9c/service/dap",
  "noDebug": true,
  "backend": "default",
  "stackTraceDepth": 50
}
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"http_server.go","path":"/Users/builduser/agent/work/3aca8f960d346a9c/_fixtures/http_server.go"},"breakpoints":[{"line":8}]}}
2022-01-10T20:26:33+01:00 debug layer=dap noDebug mode: unable to process 'setBreakpoints' request
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":false,"command":"setBreakpoints","message":"noDebug mode","body":{"error":{"id":3000,"format":"noDebug mode: unable to process 'setBreakpoints' request","showUser":false}}}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":4,"type":"request","command":"setFunctionBreakpoints","arguments":{"breakpoints":null}}
2022-01-10T20:26:33+01:00 debug layer=dap noDebug mode: unable to process 'setFunctionBreakpoints' request
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":4,"success":false,"command":"setFunctionBreakpoints","message":"noDebug mode","body":{"error":{"id":3000,"format":"noDebug mode: unable to process 'setFunctionBreakpoints' request","showUser":false}}}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":5,"type":"request","command":"pause","arguments":{"threadId":1}}
2022-01-10T20:26:33+01:00 debug layer=dap noDebug mode: unable to process 'pause' request
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":5,"success":false,"command":"pause","message":"noDebug mode","body":{"error":{"id":3000,"format":"noDebug mode: unable to process 'pause' request","showUser":false}}}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":6,"type":"request","command":"restart","arguments":{}}
2022-01-10T20:26:33+01:00 debug layer=dap Unsupported command: cannot process "restart" request
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":6,"success":false,"command":"restart","message":"Unsupported command","body":{"error":{"id":9999,"format":"Unsupported command: cannot process \"restart\" request","showUser":false}}}
2022-01-10T20:26:33+01:00 debug layer=dap [<- from client]{"seq":7,"type":"request","command":"disconnect","arguments":{"terminateDebuggee":true}}
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Terminating process 86234\n","source":{}}}
2022-01-10T20:26:33+01:00 debug layer=dap program exited with error: signal: killed
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Process 86234 has exited with status -1\n","source":{}}}
2022-01-10T20:26:33+01:00 debug layer=dap noDebug process killed
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":7,"success":true,"command":"disconnect"}
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2022-01-10T20:26:33+01:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2022-01-10T20:26:33+01:00 debug layer=dap DAP server stopping...
2022-01-10T20:26:33+01:00 debug layer=dap DAP server stopped
2022-01-10T20:26:33+01:00 debug layer=dap write tcp [::1]:49655->[::1]:49656: use of closed network connection
    server_test.go:5358: got &dap.DisconnectResponse{Response:dap.Response{ProtocolMessage:dap.ProtocolMessage{Seq:0, Type:"response"}, RequestSeq:7, Success:true, Command:"disconnect", Message:""}}, want *dap.TerminatedEvent
--- FAIL: TestNoDebug_AcceptNoRequestsButDisconnect (0.45s)
```

**Comment by suzmue** [comment]
> Not sure how the following test failure is related to this PR

I suspect it isn't, #2860 reports that it fails intermittently.

**Review by suzmue — APPROVED** [review]
LGTM

**Review by aarzilli — APPROVED** [review]
LGTM but given that users already have a workaround for this we could also *not* revert.

**Comment by hyangah** [comment]
> LGTM but given that users already have a workaround for this we could also _not_ revert.

yeah, I don't feel strongly about this - because users who want pre-#2660 can workaround currently, but with this PR, the option to create binaries in tmp locations, which I personally prefer, is completely gone (users cannot easily configure this mode). 

@polinasok @suzmue what do you think?

**Comment by polinasok** [comment]
I personally never had a problem with the original behavior, and it has been a status quo for many years without issues, right? So I this revert is ok. It's true that we have a workaround, but I don't think it is reasonable to expect the average user to study and set optional args just to get a basic debug session going. Those should really be for power users or for corner cases. This appears to be a common issue, which is reasonable to address as the default behavior. If most clients have to do this anyway, we might as well do this in the server. And then if the clients want to offer tmp dir location, they can implement that logic and set the optional arg.  It would be curious to know if vimspector has come across this complaint as well.

**Review by polinasok — APPROVED** [review]

**Comment by hyangah** [comment]
It may be a less sever issue now as dlv dap became relatively reliable and doesn't leave the temp binary everywhere less often. It also affects issues when users want to run multiple debug sessions based on files from the same directory or run multiple debug tests back-to-back (vscode-go's integration tests for example - we currently work around this problem by explicitly picking a random output file name and always setting the output field).

Significant fraction of vscode-go users are windows users, so we probably won't use it by default. So, let's revert it until other delve dap users hit the problem.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
