### PR TITLE
service/dap: use bool flag instead of channel to detect closed connection

### PR DESCRIPTION
**Pull request by polinasok**
Follow-up on #2781

### CODE REVIEW

**Comment by aarzilli** [comment]
What's synchronizing this with the goroutine that checks isClosed? isClosed gets called by the goroutine spawned by `dap.ContinueRequest` but closed is set by the goroutine in the handlerLoop, right?

**Comment by polinasok** [comment]
> What's synchronizing this with the goroutine that checks isClosed? isClosed gets called by the goroutine spawned by `dap.ContinueRequest` but closed is set by the goroutine in the handlerLoop, right?

IsClosed is checked on a goroutine started by any of the running requests (continue, configurationDone with !stopOnEntry, etc). It is closed by the main goroutine in Stop or loop goroutine in ServeDAPCodec on error (before detach) or disconnect (after detach) or in DisconnectRequest in case of accept-multiclient (when server goes on). I don't know what I was thinking. Derek asked about bool flag, and I wanted too see what it would look like given the double channel closure concern, but that's no different than just checking directly if debugger is nil before calling it. With the channel, or bool, or direct debugger check we are risking that somebody will interfere in the middle of the check-then-act logic.

I need to think about this more :(

**Comment by aarzilli** [comment]
Yes, I think both this and #2781 are broken.
There's nothing synchronizing the `s.debugger = nil` with the runUntilStop goroutine, that goroutine could be doing anything and have the rug pulled from under it.
Maybe the disconnect-and-continue case should actually stop the target and then resume it with a reduced version of the resume loop, that doesn't do logpoints or anything else weird.
Either that or disconnect and runUntilStop need to synchronize somehow.

Anyway, I think we made a change in haste and more thought should go into this. I'd leave it as is for 1.7.2, it's probably good enough.

**Comment by derekparker** [comment]
Should we revert the last commit before 1.7.3? What's the overall confidence level?

**Comment by aarzilli** [comment]
The contention window is fairly small in normal conditions, IMO it should stay.

**Comment by polinasok** [comment]
It's not an ideal solution and can race and run into issues in theory, but it does solve the very obvious and common crash in practice.

**Comment by polinasok** [comment]
> It's not an ideal solution and can race and run into issues in theory, but it does solve the very obvious and common crash in practice.

And I will keep working on this to have a better solution soon. But yeah, agree with @aarzilli that it is worth keeping it.

**Comment by derekparker** [comment]
Any updates on this?

**Comment by polinasok** [comment]
I still plan to finish this, but that won't happen for a couple of weeks.

**Comment by polinasok** [comment]
I have something else in the works, so closing this.

**Pull request closed without merging**
