### PR TITLE
proc: add minor comments

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds some comments around RequestManualStop().

### CODE REVIEW

**Comment by andreimatei** [comment]
Please let me know if this is not welcomed.

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by andreimatei** [comment]
Thanks @aarzilli. Tests are failing but that doesn't seem to be related to this PR.
I don't have access to merge it.

**Comment by derekparker** [comment]
@andreimatei thanks a lot for this, we're always open to patches which improve the documentation either internal (code comments) or external (markdown docs / wiki type stuff).

**Pull request merged**
