### PR TITLE
service/dap: clarify default attributes behavior with tests

### PR DESCRIPTION
**Pull request by polinasok**
Inspired by discussion in #2364

### CODE REVIEW

**Comment by derekparker** [comment]
cc @lggomez (the @ didn't work in the above comment).

**Comment by polinasok** [comment]
> cc @lggomez (the @ didn't work in the above comment).

Oops... Thanks!
Also, want to mention that the test failure looks unrelated. I don't see a way to rerun them though without pushing another commit.

**Review by aarzilli — APPROVED** [review]
LGTM

**Pull request merged**
