### PR TITLE
*: replace old golang.org links with new go.dev

### PR DESCRIPTION
**Pull request by alexandear**
This PR replaces the deprecated `GoDoc` links with new ones to `Go Reference` in documentation and comments.

See https://github.com/golang/go/issues/49212 for details about the deprecated `godoc`.
The badge is created at https://pkg.go.dev/badge/.

Also, replaces `github.com/go-delve/Delve` and `github.com/derekparker/delve` to `github.com/go-delve/delve`.

### CODE REVIEW

**Review by aarzilli — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by derekparker** [comment]
Please rebase and I will merge, thank you!

**Comment by alexandear** [comment]
Rebased.

**Pull request merged**
