### PR TITLE
*: un-export unnecessarily public symbols

### PR DESCRIPTION
**Pull request by aarzilli**
```
*: un-export unnecessarily public symbols

vendor: check vendor directory

Remove gitignore rule preventing vendor/modules.txt file from being
commited, add check that the vendor directory is synchronized.

```

### CODE REVIEW

**Comment by aarzilli** [comment]
I imagine we should probably discuss the _Process/_Thread thing. I didn't want to use `thread` because we use that as a variable name a lot and it would be confusing to read. _Process is for simmetry with _Thread, there would be no problem with using `process`.

**Comment by derekparker** [comment]
> I imagine we should probably discuss the _Process/_Thread thing. I didn't want to use `thread` because we use that as a variable name a lot and it would be confusing to read. _Process is for simmetry with _Thread, there would be no problem with using `process`.

How about `gdbthread`, `nativethread`, etc?

**Comment by aarzilli** [comment]
And nativeprocess/gdbprocess or just process? What about natthread instead of nativethread?

**Comment by derekparker** [comment]
> And nativeprocess/gdbprocess or just process? What about natthread instead of nativethread?

Yeah, for consistency let's name `*process` the same way. And I prefer `native*` instead of `nat*`.

**Comment by aarzilli** [comment]
nativeProcess/nativeThread/gdbProcess/gdbThread?

**Comment by derekparker** [comment]
> nativeProcess/nativeThread/gdbProcess/gdbThread?

That sgtm.

**Comment by derekparker** [comment]
Also, while we're here... we should be able to un-export all of the flag variables in `cmd/dlv/cmds/commands.go`.

**Pull request merged**
