### PR TITLE
service/dap: add test coverage for Stop()

### PR DESCRIPTION
**Pull request by polinasok**

### CODE REVIEW

**Review by aarzilli — APPROVED** [review]

**Comment by polinasok** [comment]
I am not even sure what DeepSource is unhappy about, but since it is not any code I touched in this PR, I can ignore it, right?

**Comment by aarzilli** [comment]
> I am not even sure what DeepSource is unhappy about, but since it is not any code I touched in this PR, I can ignore it, right?

Yes. Also that's bad advice and you should generally ignore it even if it was code that you wrote.

**Comment by aarzilli** [comment]
PS. same thing with the other error they added recently where they recommend using `_` for unused parameter.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
