### PR TITLE
First stab at support for Solaris/illumos.

### PR DESCRIPTION
**Pull request by andy-js**
This is my first stab at porting the delve debugger to Solaris/illumos.  This has been tested on OmniOSce LTS.

There are a few test failures which I haven't yet been able to find fixes for, though I have hacks which do allow the tests to pass (which aren't included) that may provide some idea where the problems are.  Those tests are:

<pre>
andy@omnios-lts:~/delve$ grep FAIL: test.log 
--- FAIL: TestGetG (0.15s)
--- FAIL: TestCgoStacktrace (0.58s)
--- FAIL: TestIssue1034 (0.06s)
--- FAIL: TestIssue1601 (0.43s)
--- FAIL: TestVariablesWithExternalLinking (0.58s)
--- FAIL: TestScopesAndVariablesRequests2 (0.80s)
--- FAIL: TestEvaluateRequest (0.28s)
--- FAIL: TestCgoEval (0.58s)
</pre>

Everything else passes, though I did disable a bunch of tests which are also disabled on FreeBSD.

### CODE REVIEW

**Comment by aarzilli** [comment]
See https://github.com/go-delve/delve/blob/master/Documentation/internal/portnotes.md

**Comment by andy-js** [comment]
I can't figure out what the DeepSource issues are.  When I follow the links I just end up on a blank page.

**Comment by aarzilli** [comment]
Don't worry about DeepSource. See the document I linked above for things to worry about.

**Comment by derekparker** [comment]
Closing due to inactivity. Please reopen if you would still like to work on this.

**Pull request closed without merging**
