### PR TITLE
all: import go telemetry and enable crash reporting

### PR DESCRIPTION
**Pull request by hyangah**
Imported golang.org/x/telemetry@9c0d19e to avoid
go version requirement change.

For https://github.com/go-delve/delve/issues/3815
For https://github.com/golang/go/issues/70056

### CODE REVIEW

**Comment by hyangah** [comment]
I got the following failure locally already. Keep looking.

```
--- FAIL: TestClientServer_SinglelineStringFormattedWithBigInts (1.17s)
    integration2_test.go:2786: constant: "8180A06000000000"
    integration2_test.go:2808: "9331634762088972288" "8180A06000000000"
    integration2_test.go:2808: "9331634762088972288" "8180A06000000000"
    integration2_test.go:2808: "9259436018245828608" "8080200000000000"
    integration2_test.go:2808: "9259436018245828608" "8080200000000000"
    integration2_test.go:2808: "0" "0"
panic: runtime error: index out of range [8] with length 8 [recovered]
        panic: runtime error: index out of range [8] with length 8

goroutine 1296 [running]:
testing.tRunner.func1.2({0x7b6e3c0, 0xc028d2a198})
        /Users/hakim/sdk/go1.23.1/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /Users/hakim/sdk/go1.23.1/src/testing/testing.go:1635 +0x35e
panic({0x7b6e3c0?, 0xc028d2a198?})
        /Users/hakim/sdk/go1.23.1/src/runtime/panic.go:785 +0x132
github.com/go-delve/delve/service/test_test.TestClientServer_SinglelineStringFormattedWithBigInts.func1({0x7bbf588, 0xc02a376f90}, {{0x799c3d8, 0x9}, {0xc00873a820, 0x43}, {0xc027a04690, 0x28}, {0xc027a04720, 0x2f}})
        /Users/hakim/projects/delve/service/test/integration2_test.go:2809 +0x836
github.com/go-delve/delve/service/test_test.withTestClient2Extended({0x799c3d8?, 0x100000001?}, 0xc004649750?, 0x74784d6?, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...)
        /Users/hakim/projects/delve/service/test/integration2_test.go:105 +0x191
github.com/go-delve/delve/service/test_test.TestClientServer_SinglelineStringFormattedWithBigInts(0xc0095f6820?)
        /Users/hakim/projects/delve/service/test/integration2_test.go:2775 +0x58
testing.tRunner(0xc0095f6820, 0x7ba9350)
        /Users/hakim/sdk/go1.23.1/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
        /Users/hakim/sdk/go1.23.1/src/testing/testing.go:1743 +0x390
FAIL    github.com/go-delve/delve/service/test  469.787s
FAIL
```

**Comment by aarzilli** [comment]
> I got the following failure locally already. Keep looking.

Are you using a weird version of Go?

**Comment by aarzilli** [comment]
The bump to 1.22 is problematic, 1.21 will be in the test matrix for a while.

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by aarzilli** [comment]
Thanks!

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by derekparker** [comment]
Thank you!

**Pull request merged**
