### PR TITLE
proc: skip autogenerated wrappers when stepping in and out

### LINKED ISSUE #1908: Step into autogenerated tail calls
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

2. What version of Go are you using? (`go version`)?
go version go1.13.4 linux/amd64
3. What operating system and processor architecture are you using?
ubuntu and amd64
4. What did you do?
using delve to debug.
5. What did you expect to see?
Cannot step into the method, see below info instead.
`> k8s.io/component-base/metrics.(*HistogramVec).Collect() <autogenerated>:1 (PC: 0x18b56e0)`
6. What did you see instead?
step into the method and debug step by step.

### PR DESCRIPTION
**Pull request by aarzilli**
```
proc: step into tail calls of autogenerated wrappers

Under some circumstances (when using an interface to call a method on an
embedded field, see _fixtures/ifaceembcall.go) the compiler will
autogenerate a wrapper function that uses a tail call (i.e. it ends in
an unconditional jump instruction to a different function).

Delve should be able to step into this tail call.

Fixes #1908

```

### CODE REVIEW

**Comment by chainhelen** [comment]
Hello, I have a question about `autogenrated`, is it possible to detect this case ?  

```
package main

import (
	"fmt"
)

type Iface interface {
	Blah() string
}

type A struct {
	a int
}

func (A) Blah() string {
	return "blah"
}

func main() {
	var iface Iface = A{a: 1}
	s := iface.Blah()    // line 21
	fmt.Printf("%s\n", s)
}

```
set breakpoint at line 21 then step, we can see it also enter `autogenerated`
```
> main.(*A).Blah() <autogenerated>:1 (PC: 0x4ac14f)
```  

Ps: 
```
(dlv) disassemble
TEXT main.(*A).Blah(SB) <autogenerated>
	<autogenerated>:1	0x4ac140	64488b0c25f8ffffff	mov rcx, qword ptr fs:[0xfffffff8]
	<autogenerated>:1	0x4ac149	483b6110		cmp rsp, qword ptr [rcx+0x10]
	<autogenerated>:1	0x4ac14d	766f			jbe 0x4ac1be
=>	<autogenerated>:1	0x4ac14f	4883ec38		sub rsp, 0x38
	<autogenerated>:1	0x4ac153	48896c2430		mov qword ptr [rsp+0x30], rbp
	<autogenerated>:1	0x4ac158	488d6c2430		lea rbp, ptr [rsp+0x30]
	<autogenerated>:1	0x4ac15d	488b5920		mov rbx, qword ptr [rcx+0x20]
	<autogenerated>:1	0x4ac161	4885db			test rbx, rbx
	<autogenerated>:1	0x4ac164	7562			jnz 0x4ac1c8
	<autogenerated>:1	0x4ac166	0f57c0			xorps xmm0, xmm0
	<autogenerated>:1	0x4ac169	0f11442448		movups xmmword ptr [rsp+0x48], xmm0
	<autogenerated>:1	0x4ac16e	48837c244000		cmp qword ptr [rsp+0x40], 0x0
	<autogenerated>:1	0x4ac174	7502			jnz 0x4ac178
	<autogenerated>:1	0x4ac176	eb40			jmp 0x4ac1b8
	<autogenerated>:1	0x4ac178	488b442440		mov rax, qword ptr [rsp+0x40]
	<autogenerated>:1	0x4ac17d	8400			test byte ptr [rax], al
	<autogenerated>:1	0x4ac17f	488b00			mov rax, qword ptr [rax]
	<autogenerated>:1	0x4ac182	4889442418		mov qword ptr [rsp+0x18], rax
	<autogenerated>:1	0x4ac187	48890424		mov qword ptr [rsp], rax
	<autogenerated>:1	0x4ac18b	e830feffff		call $main.A.Blah
	<autogenerated>:1	0x4ac190	488b442410		mov rax, qword ptr [rsp+0x10]
	<autogenerated>:1	0x4ac195	488b4c2408		mov rcx, qword ptr [rsp+0x8]
	<autogenerated>:1	0x4ac19a	48894c2420		mov qword ptr [rsp+0x20], rcx
	<autogenerated>:1	0x4ac19f	4889442428		mov qword ptr [rsp+0x28], rax
	<autogenerated>:1	0x4ac1a4	48894c2448		mov qword ptr [rsp+0x48], rcx
	<autogenerated>:1	0x4ac1a9	4889442450		mov qword ptr [rsp+0x50], rax
	<autogenerated>:1	0x4ac1ae	488b6c2430		mov rbp, qword ptr [rsp+0x30]
	<autogenerated>:1	0x4ac1b3	4883c438		add rsp, 0x38
	<autogenerated>:1	0x4ac1b7	c3			ret
	<autogenerated>:1	0x4ac1b8	e8c3baf5ff		call $runtime.panicwrap
	main.go:1		0x4ac1bd	90			nop
	main.go:1		0x4ac1be	e81dccfaff		call $runtime.morestack_noctxt
	main.go:1		0x4ac1c3	e978ffffff		jmp $main.(*A).Blah
	main.go:1		0x4ac1c8	488d7c2440		lea rdi, ptr [rsp+0x40]
	main.go:1		0x4ac1cd	48393b			cmp qword ptr [rbx], rdi
	main.go:1		0x4ac1d0	7594			jnz 0x4ac166
	main.go:1		0x4ac1d2	488923			mov qword ptr [rbx], rsp
	main.go:1		0x4ac1d5	eb8f			jmp 0x4ac166
```

**Comment by aarzilli** [comment]
@chainhelen This isn't about preventing Delve from entering autogenerated wrappers, it's about teaching Delve how to follow the tail call that is inserted into some autogenerated wrappers.

**Comment by chainhelen** [comment]
Oh, got it, thx.

**Comment by derekparker** [comment]
This is great, definitely an improvement.

Makes me wonder if we should hide the autogenerated wrapper from the user by default though, similar to how we skip function prologues.

**Comment by aarzilli** [comment]
We could do it in setStepIntoBreakpoint, we could disassemble the target function and figure out the real target. It would have to be recursive because there could be multiple layers of autogenerated wrappers going on.

**Comment by derekparker** [comment]
> We could do it in setStepIntoBreakpoint, we could disassemble the target function and figure out the real target. It would have to be recursive because there could be multiple layers of autogenerated wrappers going on.

I think that would be a better experience for the user. Showing them the autogenerated wrapper really isn't beneficial.

**Comment by aarzilli** [comment]
Done. It's a bit more involved but better for the user.

**Pull request merged**
