### PR TITLE
pkg/proc: Fix Windows ebpf build errors

### LINKED ISSUE #2636: Failing Installation on Windows Machine
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? Latest in github
2. What version of Go are you using? (`go version`)? V1.15
3. What operating system and processor architecture are you using? Windows 64
4. What did you do? Tried installing delve using: go get -u -v github.com/go-delve/delve/cmd/dlv
5. What did you expect to see? Successfull installation
6. What did you see instead?

```
github.com/go-delve/delve (download)
created GOPATH=C:\Users\kbuilder\Go; see 'go help gopath'
github.com/go-delve/delve/pkg/proc/macutil
github.com/go-delve/delve/vendor/golang.org/x/sys/internal/unsafeheader
github.com/go-delve/delve/vendor/github.com/shurcooL/sanitized_anchor_name
github.com/go-delve/delve/vendor/github.com/hashicorp/golang-lru/simplelru
github.com/go-delve/delve/vendor/github.com/konsorten/go-windows-terminal-sequences
github.com/go-delve/delve/vendor/github.com/mattn/go-isatty
github.com/go-delve/delve/vendor/gopkg.in/yaml.v2
github.com/go-delve/delve/pkg/goversion
github.com/go-delve/delve/vendor/github.com/cosiner/argv
github.com/go-delve/delve/pkg/dwarf/util
github.com/go-delve/delve/vendor/github.com/sirupsen/logrus
github.com/go-delve/delve/pkg/dwarf/regnum
github.com/go-delve/delve/pkg/elfwriter
github.com/go-delve/delve/pkg/astutil
github.com/go-delve/delve/pkg/version
github.com/go-delve/delve/vendor/golang.org/x/arch/arm64/arm64asm
github.com/go-delve/delve/pkg/terminal/colorize
github.com/go-delve/delve/vendor/golang.org/x/arch/x86/x86asm
github.com/go-delve/delve/pkg/dwarf/frame
github.com/go-delve/delve/pkg/dwarf/op
github.com/go-delve/delve/pkg/dwarf/line
github.com/go-delve/delve/pkg/logflags
github.com/go-delve/delve/vendor/golang.org/x/sys/windows
github.com/go-delve/delve/pkg/dwarf/godwarf
github.com/go-delve/delve/vendor/github.com/peterh/liner
github.com/go-delve/delve/vendor/go.starlark.net/internal/spell
github.com/go-delve/delve/pkg/config
github.com/go-delve/delve/vendor/go.starlark.net/syntax
github.com/go-delve/delve/vendor/github.com/mattn/go-colorable
github.com/go-delve/delve/pkg/dwarf/loclist
github.com/go-delve/delve/pkg/gobuild
github.com/go-delve/delve/pkg/dwarf/reader
github.com/go-delve/delve/pkg/proc/internal/ebpf
github.com/go-delve/delve/service/internal/sameuser
github.com/go-delve/delve/vendor/github.com/google/go-dap
github.com/go-delve/delve/vendor/github.com/inconshreveable/mousetrap
github.com/go-delve/delve/vendor/github.com/spf13/pflag
github.com/go-delve/delve/vendor/github.com/russross/blackfriday/v2
github.com/go-delve/delve/pkg/proc
github.com/go-delve/delve/vendor/go.starlark.net/resolve
github.com/go-delve/delve/vendor/go.starlark.net/internal/compile
github.com/go-delve/delve/vendor/github.com/cpuguy83/go-md2man/v2/md2man
github.com/go-delve/delve/vendor/github.com/spf13/cobra
github.com/go-delve/delve/vendor/go.starlark.net/starlark
github.com/go-delve/delve/vendor/github.com/spf13/cobra/doc
github.com/go-delve/delve/service/api
github.com/go-delve/delve/pkg/proc/amd64util
github.com/go-delve/delve/pkg/proc/winutil
github.com/go-delve/delve/pkg/proc/core/minidump
github.com/go-delve/delve/pkg/proc/native
github.com/go-delve/delve/pkg/proc/linutil
github.com/go-delve/delve/pkg/locspec
# github.com/go-delve/delve/pkg/proc/native
C:\Users\kbuilder\Go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:49:5: cannot use &nativeProcess literal (type *nativeProcess) as type proc.ProcessInternal in assignment:
	*nativeProcess does not implement proc.ProcessInternal (missing GetBufferedTracepoints method)
C:\Users\kbuilder\Go\src\github.com\go-delve\delve\pkg\proc\native\proc_windows.go:494:59: undefined: proc.UProbeArgMap
github.com/go-delve/delve/pkg/proc/core
github.com/go-delve/delve/pkg/proc/gdbserial
```

### PR DESCRIPTION
**Pull request by derekparker**
Fixes #2636

### CODE REVIEW

**Comment by derekparker** [comment]
I'm surprised this wasn't caught by CI.

**Review by hyangah — APPROVED** [review]
Not sure why CI didn't catch this - as far as I see cmd/dlv/delve_test should build. From the last run at refs/heads/master ran only 45 tests and still marked as passed. https://delve.teamcity.com/buildConfiguration/Delve_windows_amd64_1_17?mode=builds#all-projects

**Comment by derekparker** [comment]
@hyangah yeah I think there's an issue with the CI runner or something. Clearly from these logs the build did actually fail, but the CI runner did not mark the job as failed: https://delve.teamcity.com/buildConfiguration/Delve_windows_amd64_1_17/18164?buildTab=log&focusLine=519&linesState=519.

cc @nd any thoughts on why this would be happening? Is this a misconfiguration on our end?

**Comment by nd** [comment]
@derekparker looks like compilation errors are not reported in json, that's why teamcity misses them. I hope reporting test exit code (#2638) will make it fail.

**Comment by derekparker** [comment]
@nd looks like your patch helped, but now I can't see the test run output in the log and this Windows run was marked a failure but I can't figure out why other than `make test` seems to have exited with status code 1.

**Comment by nd** [comment]
@derekparker json output is shown if you select 'View: Verbose' in the top of the page. You can also download full build log, it might be more convenient to view it in the editor inside the browser. Filed an issue for better output from go test: https://youtrack.jetbrains.com/issue/TW-72558.

It looks like your build failed to install gcc. I've rerun it, now it shows which test failed: https://delve.teamcity.com/viewLog.html?buildId=18326&buildTypeId=Delve_windows_amd64_1_17&tab=buildResultsDiv&branch_Delve_windows_amd64=pull%2F2637

**Comment by aarzilli** [comment]
The tests were failing because it couldn't install mingw due to a transient failure of sourceforge. Now TestVariableLoadingOfLongStrings is failing but that's probably an old error we never noticed.

**Review by aarzilli — APPROVED** [review]

**Pull request merged**
