### PR TITLE
Run CI tests on windows/arm64 agents

### PR DESCRIPTION
**Pull request by qmuntal**
Now that we have windows/arm64 agents (see #3197), let's try to exercise them.

### CODE REVIEW

**Comment by qmuntal** [comment]
@derekparker is there any setup missing? Can't see tjhe windows/arm64 subproject in teamcity:

image

**Comment by derekparker** [comment]
@qmuntal looking at the TeamCity agent admin page it seems to think the windows/arm64 agent is disconnected right now.

**Comment by qmuntal** [comment]
> @qmuntal looking at the TeamCity agent admin page it seems to think the windows/arm64 agent is disconnected right now.

I think I have something wrong in the agent configuration. It unregisters every now and them and registers again after a while.

But I think this problem is separated from what I was saying about the subproject. Have you tried creating it a windows/arm64 subproject from the dashboard?

**Comment by aarzilli** [comment]
AFAIK changes to the configuration of teamcity from the dashboards are not allowed: all the targets are created from the settings.kts file that is committed in the repository. The windows/arm64 target will only appear after a change like the one in this PR is merged.

**Comment by qmuntal** [comment]
> AFAIK changes to the configuration of teamcity from the dashboards are not allowed: all the targets are created from the settings.kts file that is committed in the repository. The windows/arm64 target will only appear after a change like the one in this PR is merged.

Makes sense. Then I'm limiting the scope of this PR to just set up windows/arm64 subproject and run a stub command instead of the build + test steps. I'll fix the build scripts and failing unit tests in a follow up PR.

**Review by aarzilli — APPROVED** [review]

**Pull request merged**
