### PR TITLE
*: Remove dependency on logrus

### LINKED ISSUE #2037: Dependencies in go.mod are out of sync
1. What version of Delve are you using (`dlv version`)?
2f295f310d543f0d155ca1ea9a8a1e1288afd7b6

2. What version of Go are you using? (`go version`)?
go1.14.2 

3. What operating system and processor architecture are you using?
windows/amd64

4. What did you do?
Run `go mod tidy` and `go mod vendor`.

5. What did you expect to see?
Nothing should be changed in `go.mod` or in the `vendor/` directory.

6. What did you see instead?
```
git diff
diff --git a/go.mod b/go.mod
index 76275bc9..811a4b9c 100644
--- a/go.mod
+++ b/go.mod
@@ -4,13 +4,14 @@ go 1.11

 require (
        github.com/cosiner/argv v0.0.0-20170225145430-13bacc38a0a5
-       github.com/cpuguy83/go-md2man v1.0.10 // indirect
        github.com/creack/pty v1.1.9
        github.com/google/go-dap v0.2.0
        github.com/hashicorp/golang-lru v0.5.4
        github.com/inconshreveable/mousetrap v1.0.0 // indirect
        github.com/mattn/go-colorable v0.0.0-20170327083344-ded68f7a9561
        github.com/mattn/go-isatty v0.0.3
+       github.com/onsi/ginkgo v1.12.0 // indirect
+       github.com/onsi/gomega v1.9.0 // indirect
        github.com/peterh/liner v0.0.0-20170317030525-88609521dc4b
        github.com/pkg/profile v0.0.0-20170413231811-06b906832ed0
        github.com/sirupsen/logrus v0.0.0-20180523074243-ea8897e79973
@@ -19,7 +20,9 @@ require (
        github.com/stretchr/testify v1.3.0 // indirect
        go.starlark.net v0.0.0-20190702223751-32f345186213
        golang.org/x/arch v0.0.0-20190927153633-4e8777c89be4
-       golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb
+       golang.org/x/sys v0.0.0-20191120155948-bd437916bb0e
        golang.org/x/tools v0.0.0-20191127201027-ecd32218bd7f
-       gopkg.in/yaml.v2 v2.2.1
+       gopkg.in/airbrake/gobrake.v2 v2.0.9 // indirect
+       gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2 // indirect
+       gopkg.in/yaml.v2 v2.2.4
 )
```

Shall I send a PR to rectify this?

### PR DESCRIPTION
**Pull request by aarzilli**
```
*: Remove dependency on logrus

We use logrus as a thin layer around fmt.Fprintf, however it introduces
a large number of dependencies, including:

* two different testing frameworks (testify, ginkgo)
* bindings to the application monitoring service "airbrake"
* an implementation of the ssh protocol
* the entirety of golang.org/x/crypto

This commit replace logrus with a copy of the 50 lines of logrus we
actually use.

Fixes #2037

```

### CODE REVIEW

**Comment by aarzilli** [comment]
I think 3000 lines of code is a bit much for a logging library. The replacement does almost nothing but it's the almost nothing that we are using. If more features of logrus are needed in the future we can reevaluate its inclusion easily since the impact of this outside of logflags is pretty much nothing.

**Comment by qingyunha** [comment]
I test with lastest logrus, it doesn't seem to have those dependencies.

```sh
$ cat t.go
package main

import (
        "github.com/sirupsen/logrus"
)

func main() {
        logrus.Info("hello world")
}



$ cat go.mod
module llog

go 1.13

require github.com/sirupsen/logrus v1.6.0



$ cat go.sum
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/konsorten/go-windows-terminal-sequences v1.0.3 h1:CE8S1cTafDpPvMhIxNJKvHsGVBgn1xWYf1NbHQhywc8=
github.com/konsorten/go-windows-terminal-sequences v1.0.3/go.mod h1:T0+1ngSBFLxvqU3pZ+m/2kptfBszLMUkC4ZK/EgS/cQ=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/sirupsen/logrus v1.6.0 h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
github.com/sirupsen/logrus v1.6.0/go.mod h1:7uNnSEd1DgxDLC74fIahvMZmmYsHGZGEOFrfsX/uA88=
github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
golang.org/x/sys v0.0.0-20190422165155-953cdadca894 h1:Cz4ceDQGXuKRnVBDTS23GTn/pU5OE2C0WrNTOYK1Uuc=
golang.org/x/sys v0.0.0-20190422165155-953cdadca894/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=



$  ls vendor/
github.com/  golang.org/  modules.txt



$ cat vendor/modules.txt
# github.com/konsorten/go-windows-terminal-sequences v1.0.3
github.com/konsorten/go-windows-terminal-sequences
# github.com/sirupsen/logrus v1.6.0
github.com/sirupsen/logrus
# golang.org/x/sys v0.0.0-20190422165155-953cdadca894
golang.org/x/sys/unix
```

**Comment by aarzilli** [comment]
@qingyunha that's also acceptable #2048

**Comment by derekparker** [comment]
Closing for now in favor of #2048. We may still want to revisit possibly taking logrus out and replacing with a smaller version we roll ourselves (like this PR), but I think just getting rid of the dependencies we don't actually need is fine for now.

**Pull request closed without merging**
