### PR TITLE
service/dap: support starting Debugger in Run and remote attach mode

### PR DESCRIPTION
**Pull request by polinasok**
New command-line interface coming in a separate PR

### CODE REVIEW

**Comment by polinasok** [comment]
What does this error mean?
```
DAP server listening at: [::]:57492
Connecting to server at: [::]:57492
2021-08-06T07:13:51Z error layer=dap runtime error: ptraceGetLwpInfo err no such process -1
--- FAIL: TestAttachRemoteContinueOnEntry (0.18s)
    server_test.go:5097: got &dap.StoppedEvent{Event:dap.Event{ProtocolMessage:dap.ProtocolMessage{Seq:0, Type:"event"}, Event:"stopped"}, Body:dap.StoppedEventBody{Reason:"exception", Description:"runtime error", ThreadId:0, PreserveFocusHint:false, Text:"ptraceGetLwpInfo err no such process -1", AllThreadsStopped:true, HitBreakpointIds:[]int(nil)}}, want *dap.TerminatedEvent
DAP server listening at: [::]:57494
2021-08-06T07:13:51Z error layer=dap detach returned error: device busy

```

**Comment by aarzilli** [comment]
I was under the impression that for this feature was going to be implemented by letting users start delve in the old way (`dlv debug --headless ...`) with the argument behind the decision being that it wouldn't break existing documentation. It seems that this PR is going into a different direction. What's the overriding reason for doing so? It also seems that this changeset also highlights another problem: a dap.Server object can now exist without a connected client, every `s.send` call is suspicious and needs to be audited to determine whether it can happen without a client, hence the `logToConsoleIfConn` and presumably more IfConns to come if the continueOnEntry is also implemented.

**Comment by polinasok** [comment]
> I was under the impression that for this feature was going to be implemented by letting users start delve in the old way (`dlv debug --headless ...`) with the argument behind the decision being that it wouldn't break existing documentation. It seems that this PR is going into a different direction. What's the overriding reason for doing so?

`dlv debug --headless` is indeed the final destination, but I wanted to get there gradually, with the dlv-dap command without multi-client and such being an intermediate version that can highlight any discrepancies we must address (e.g. on shutdown) and can also unblock [Cloud Code](https://cloud.google.com/code) to try out dlv-dap while we work on the full merger.

> It also seems that this changeset also highlights another problem: a dap.Server object can now exist without a connected client, every `s.send` call is suspicious and needs to be audited to determine whether it can happen without a client, hence the `logToConsoleIfConn` and presumably more IfConns to come if the continueOnEntry is also implemented.

This is only true for shutdown because the same shutdown code is currently reused no matter how things are shut down. We report explicit progress to the user via the Debug Console because we have had confusion as to whether things shut down behind the scenes or not. One might argue that even after `dlv --headless` merger it would be useful to have such shutdown logging available as well if the dap client is still connected. But if that is a concern, we can have separate shutdown code depending on how things were launched. We need to sort how Stop will be called with the merger anyway. And on a related note, why is rpc's `Stop()` only calling `Detach` and not `Halt+Detach`?

Anything else that the server does can only happen in response to a request from a client, so unless we also want to safeguard for unexpected connection interruptions, not additional auditing is needed. As for continue on entry, it would be nice to have it available without multi-client, by just calling the continue command after attaching the debugger.

**Comment by aarzilli** [comment]
> > I was under the impression that for this feature was going to be implemented by letting users start delve in the old way (`dlv debug --headless ...`) with the argument behind the decision being that it wouldn't break existing documentation. It seems that this PR is going into a different direction. What's the overriding reason for doing so?
> 
> `dlv debug --headless` is indeed the final destination, but I wanted to get there gradually, with the dlv-dap command without multi-client and such being an intermediate version that can highlight any discrepancies we must address (e.g. on shutdown) and can also unblock [Cloud Code](https://cloud.google.com/code) to try out dlv-dap while we work on the full merger.

I don't think this is true, that this is a gradual path to there. If dap.Server never starts a dabug session without a client connection then it doesn't even need to exist unless a client is connected. Also the entire initialization of the debugger object would happen elsewhere and you would end up with three different initialization paths for dap.Server:

* not connected to a client, but has a debugger object (this PR)
* connected to a client, no debugger object: it will be created via a Launch request (normal mode)
* connected to a client, with a debugger object, Launch request needs to be ignored (`dlv --headless`)

It's tricky to get it right. FWIW I think the current PR does not, it calls logToConsoleIfConn but later in the same method calls s.send with a nil conn, AFAICT either the logToConsoleIfConn is unnecessary or the send will SIGSEGV.

> > It also seems that this changeset also highlights another problem: a dap.Server object can now exist without a connected client, every `s.send` call is suspicious and needs to be audited to determine whether it can happen without a client, hence the `logToConsoleIfConn` and presumably more IfConns to come if the continueOnEntry is also implemented.
> 
> This is only true for shutdown because the same shutdown code is currently reused no matter how things are shut down.

Not if the `TODO(polina): support continue on entry` is implemented.

> We report explicit progress to the user via the Debug Console and via logging because we have had confusion as to whether things shut down behind the scenes or not. One might argue that even after `dlv --headless` merger it would be useful to have such shutdown logging both on client and server sides. But if that is a concern, we can have separate shutdown code depending on how things were launched. We need to sort out how Stop will be called with the merger anyway. And on a related note, why is rpc's `Stop()` only calling `Detach` and not `Halt+Detach`?

AFAIK it only gets there if the target process is stopped or terminated.

**Comment by polinasok** [comment]
> If dap.Server never starts a dabug session without a client connection then it doesn't even need to exist unless a client is connected. 

I am not sure what you mean.

> Also the entire initialization of the debugger object would happen elsewhere and you would end up with three different initialization paths for dap.Server.

Yes, that would be the case.

> connected to a client, with a debugger object, Launch request needs to be ignored (dlv --headless)

Is that the case though? I planned both (1) and (3) to behave the same during client initialization with the debugger already present.

- launch + program => start dlv, tell it to launch program
- launch + program + host/port => connect to dlv, tell it to launch program
- attach + host/port => connect to dlv, expect it to already have running program 

> It's tricky to get it right. FWIW I think the current PR does not, it calls logToConsoleIfConn but later in the same method calls s.send with a nil conn, AFAICT either the logToConsoleIfConn is unnecessary or the send will SIGSEGV.

Which method are you referring to? I tested this both manually with kill and added TestNoClient to server_test.go. Where do you expect this to crash?

> > And on a related note, why is rpc's Stop() only calling Detach and not Halt+Detach?

> AFAIK it only gets there if the target process is stopped or terminated.

Not if Stop is triggered when the server is force-killed with a signal while the program is running.

**Comment by aarzilli** [comment]
> > If dap.Server never starts a dabug session without a client connection then it doesn't even need to exist unless a client is connected.
> 
> I am not sure what you mean.

With the `--headless` mode serving DAP and JSON-RPC multiplexed it would work like this:

* rpccommon/server.go` listen on the socket and accepts connections from clients
* after a client is connected it looks at the first byte sent on the connection to determine which protocol is used
* if it's DAP it starts dap.Server

dap.Server wouldn't start the debugger and wouldn't be even instantiated until there's a connection from a client to serve.

> 
> > Also the entire initialization of the debugger object would happen elsewhere and you would end up with three different initialization paths for dap.Server.
> 
> Yes, that would be the case.
> 
> > connected to a client, with a debugger object, Launch request needs to be ignored (dlv --headless)
> 
> Is that the case though? I planned both (1) and (3) to behave the same during client initialization with the debugger already present.

For responding to the launch request, yes, but in (1) you have a Server object without a connection to a client and in (3) you don't.

> > It's tricky to get it right. FWIW I think the current PR does not, it calls logToConsoleIfConn but later in the same method calls s.send with a nil conn, AFAICT either the logToConsoleIfConn is unnecessary or the send will SIGSEGV.
> 
> Which method are you referring to? I tested this both manually with kill and added TestNoClient to server_test.go. Where do you expect this to crash?

You're right, I was just reading the diff wrong, there should be no possible sends in the path that has logToConsoleIfConn, but it doesn't matter it's an exceptional state that the code can be in that will need to be accounted for on every change.

> > > And on a related note, why is rpc's Stop() only calling Detach and not Halt+Detach?
> 
> > AFAIK it only gets there if the target process is stopped or terminated.
> 
> Not if Stop is triggered when the server is force-killed with a signal while the program is running.

Why should it work differently?

**Comment by hyangah** [comment]
> > > If dap.Server never starts a dabug session without a client connection then it doesn't even need to exist unless a client is connected.
> > 
> > 
> > I am not sure what you mean.
> 
> With the `--headless` mode serving DAP and JSON-RPC multiplexed it would work like this:
> 
> * rpccommon/server.go` listen on the socket and accepts connections from clients
> * after a client is connected it looks at the first byte sent on the connection to determine which protocol is used
> * if it's DAP it starts dap.Server
> 
> dap.Server wouldn't start the debugger and wouldn't be even instantiated until there's a connection from a client to serve.
> 
> > > Also the entire initialization of the debugger object would happen elsewhere and you would end up with three different initialization paths for dap.Server.
> > 
> > 
> > Yes, that would be the case.
> > > connected to a client, with a debugger object, Launch request needs to be ignored (dlv --headless)
> > 
> > 
> > Is that the case though? I planned both (1) and (3) to behave the same during client initialization with the debugger already present.
> 
> For responding to the launch request, yes, but in (1) you have a Server object without a connection to a client and in (3) you don't.
> 
> > > It's tricky to get it right. FWIW I think the current PR does not, it calls logToConsoleIfConn but later in the same method calls s.send with a nil conn, AFAICT either the logToConsoleIfConn is unnecessary or the send will SIGSEGV.
> > 
> > 
> > Which method are you referring to? I tested this both manually with kill and added TestNoClient to server_test.go. Where do you expect this to crash?
> 
> You're right, I was just reading the diff wrong, there should be no possible sends in the path that has logToConsoleIfConn, but it doesn't matter it's an exceptional state that the code can be in that will need to be accounted for on every change.
> 
> > > > And on a related note, why is rpc's Stop() only calling Detach and not Halt+Detach?
> > 
> > 
> > > AFAIK it only gets there if the target process is stopped or terminated.
> > 
> > 
> > Not if Stop is triggered when the server is force-killed with a signal while the program is running.
> 
> Why should it work differently?

Confusing. When the delve headless server is force-killed with a signal, how is the target program getting killed?
(OTOH, I guess killing non-dap headless server while target program is running is a rare event given that headless server runs in background and most well-behaved clients (dlv terminal or other clients) would send halt first before disconnecting)

**Comment by polinasok** [comment]
> a dap.Server object can now exist without a connected client, every `s.send` call is suspicious and needs to be audited to determine whether it can happen without a client, hence the `logToConsoleIfConn` and presumably more IfConns to come if the continueOnEntry is also implemented.

Interestingly, in the rpc server with --continue, the handler also can call send without a connected client on forced shutdown. But it just results in a write error because there used to be a client.
```
2021-08-27T01:06:19-07:00 error layer=rpc writing response:write tcp 127.0.0.1:58310->127.0.0.1:58311: use of closed network connection
```

**Comment by aarzilli** [comment]
> It also adds logic to Run that will not apply because rpccommon Run will be used instead. So that part won't get reused here

So let's not add it.

> I don't see what the harm is in having this mode as well, especially while the other version is still being worked out.

The harm is more special cases.

**Comment by polinasok** [comment]
All right. Let's see where the other version takes me.

**Comment by soffieswan043** [comment]
#2648 (comment)

**Review by soffieswan043 — COMMENTED** [review]
#2648 (comment)

**Pull request closed without merging**
