### PR TITLE
delve: Separate amd64-arch code from the project.

### PR DESCRIPTION
**Pull request by hengwu0**
In order to implement other arch( arm64 ), we need to separate amd64-arch code firstly. This patch do not change any code, except _ArchInfo_ function in _arch_amd64.go_. But i also correct the _dwarf_expr_test.go_, to make sure the testsuits pass.

#118

### CODE REVIEW

**Comment by hengwu0** [comment]
> In order to implement other arch( arm64 ), we need to separate amd64-arch code firstly. This patch do not change any code, except _ArchInfo_ function in _arch_amd64.go_. But i also correct the _dwarf_expr_test.go_, to make sure the testsuits pass.

#118

**Comment by aarzilli** [comment]
No, I don't think this is what we want. I can't see any reason why the AMD64 implementation of Arch should be compiled in conditionally. I think an ARM64 build of delve should be able to read AMD64 core files and vice versa. Same thing goes from every other change. There's a reason linux_amd64_core was named linux_amd64_core and not core_linux_amd64, the reason is that it should be compiled in, no matter what architecture or operating system is doing the build.

**Comment by hengwu0** [comment]
> No, I don't think this is what we want. I can't see any reason why the AMD64 implementation of Arch should be compiled in conditionally. I think an ARM64 build of delve should be able to read AMD64 core files and vice versa. Same thing goes from every other change. There's a reason linux_amd64_core was named linux_amd64_core and not core_linux_amd64, the reason is that it should be compiled in, no matter what architecture or operating system is doing the build.

Okey, I agree this idea can let delve be easy-to-use, but hard to code of course. Because that means we should use different funcs according to the arch. I think the best code is like `go objdump` tool, it calls the methods in the class, and different arch use different class. Or just add an parameter in each func which we need. Whatever, we may need to change almost 20 files showed in this patch, to adapt multiple architectures. What's your idea, use class definition? I hope I can help, to let it support arm64.

**Comment by aarzilli** [comment]
Yes, it should be similar to what `go objdump` does. 

> Whatever, we may need to change almost 20 files showed in this patch, to adapt multiple architectures

I'm not sure how many files you would need to change because I'm not sure what the scope of this PR would be. I suggest you do not try to simultaneously port proc/core, proc/native and proc/gdbserial all at once to arm64 and instead just pick one backend and only do that one.

**Comment by hengwu0** [comment]
> I'm not sure what the scope of this PR would be.

This PR will be closed, because there is no need to separate amd64 code with that compatibility goals.

>  I suggest you do not try to simultaneously port proc/core, proc/native and proc/gdbserial all at once to arm64 and instead just pick one backend and only do that one.

I think I will pick _proc/native_, because the local debug is a foundamental function i think. The arch, regs, disasm already had architecture attribute, beside _/proc/stack.go_. As arm64 need different method to parse stack-frame,  i think it should be transformed first.

**Comment by aarzilli** [comment]
stack.go executes instructions read from debug_frame, I expect few changes to that file.

**Comment by hengwu0** [comment]
> stack.go executes instructions read from debug_frame, I expect few changes to that file.

yes, but the instructions are different between arm64 and amd64. So, there may have two things: 
1、pack stack func with interface, or add arch parameter.
2、separate amd64-arch code from proc/native.
the first one seems code frame related, hope you can help. Thanks.

**Pull request closed without merging**
