### PR TITLE
split testing load between more CI services

### PR DESCRIPTION
**Pull request by aarzilli**

### CODE REVIEW

**Comment by derekparker** [comment]
Do we need to enable actions on this repo or something to get this working properly?

**Comment by aarzilli** [comment]
I think so. I'm not sure. Maybe it needs to be merged before it becomes available?

**Comment by derekparker** [comment]
I think the yaml file has to be placed in `.github/workflows`.

**Comment by aarzilli** [comment]
Done.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
