### PR TITLE
proc/core: return true for calls to Recorded

### LINKED ISSUE #2978: Wrong RPCServer.Recorded result (Recorded = false) for core dumps
1. What version of Delve are you using (`dlv version`)?

```
Version: 1.8.2
Build: aac4e19c243d1ceb63de94c87b936d90dca6441e
```

2. What version of Go are you using? (`go version`)?

`go version go1.18 linux/amd64`, happens in older go versions as well

3. What operating system and processor architecture are you using?

```
linux/amd64
```

4. What did you do?

examined a core dump created from

```
package main

func main() {
	fail(nil)
}

//go:noinline
func fail(p *string) {
  if true {
	  println(*p)
  }
}
```

using `dlv core executable coreDump` command.

5. What did you expect to see?

`RPCServer.Recorded` command returns `Recorded: true`

6. What did you see instead?

`Recorded: false`:

```
API server listening at: 127.0.0.1:42973
2022-04-21T15:49:27+02:00 debug layer=rpc API server pid = 107074
2022-04-21T15:49:27+02:00 debug layer=rpc serving JSON-RPC on new connection
2022-04-21T15:49:27+02:00 debug layer=rpc (async 1) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2022-04-21T15:49:27+02:00 debug layer=rpc (async 1) -> rpc2.StateOut{"State":{"Pid":0,"Running":false,"Recording":false,"CoreDumping":false,"currentThread":{"id":106778,"pc":4562369,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":168,"function":{"name":"runtime.raise","value":4562336,"type":0,"goType":0,"optimized":true},"goroutineID":1,"ReturnValues":null,"CallReturn":false},"currentGoroutine":{"id":1,"currentLoc":{"pc":4562369,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":168,"function":{"name":"runtime.raise","value":4562336,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4568313,"file":"/home/nd/tmp/warning/core.go","line":8,"function":{"name":"main.fail","value":4568288,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4565413,"file":"\u003cautogenerated\u003e","line":1,"function":{"name":"runtime.newproc","value":4565376,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4401216,"file":"/home/nd/go/go1.18/src/runtime/proc.go","line":145,"function":{"name":"runtime.main","value":4401216,"type":0,"goType":0,"optimized":true}},"threadID":106778,"status":2,"waitSince":0,"waitReason":14,"unreadable":""},"Threads":[{"id":106778,"pc":4562369,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":168,"function":{"name":"runtime.raise","value":4562336,"type":0,"goType":0,"optimized":true},"goroutineID":1,"ReturnValues":null,"CallReturn":false},{"id":106779,"pc":4563779,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":553,"function":{"name":"runtime.futex","value":4563744,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null,"CallReturn":false},{"id":106780,"pc":4563779,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":553,"function":{"name":"runtime.futex","value":4563744,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null,"CallReturn":false},{"id":106781,"pc":4563779,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":553,"function":{"name":"runtime.futex","value":4563744,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null,"CallReturn":false},{"id":106782,"pc":4563779,"file":"/home/nd/go/go1.18/src/runtime/sys_linux_amd64.s","line":553,"function":{"name":"runtime.futex","value":4563744,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null,"CallReturn":false}],"NextInProgress":false,"WatchOutOfScope":[],"exited":false,"exitStatus":0,"When":""}} error: ""
2022-04-21T15:49:27+02:00 debug layer=rpc <- RPCServer.GetVersion(api.GetVersionIn{})
2022-04-21T15:49:27+02:00 debug layer=rpc -> *api.GetVersionOut{"DelveVersion":"Version: 1.8.2\nBuild: aac4e19c243d1ceb63de94c87b936d90dca6441e","APIVersion":2,"Backend":"core","TargetGoVersion":"Go cmd/compile go1.18","MinSupportedVersionOfGo":"1.16.0","MaxSupportedVersionOfGo":"1.18.0"} error: ""
2022-04-21T15:49:27+02:00 debug layer=rpc <- RPCServer.Recorded(rpc2.RecordedIn{})
2022-04-21T15:49:27+02:00 debug layer=rpc -> *rpc2.RecordedOut{"Recorded":false,"TraceDirectory":""} error: ""
2022-04-21T15:49:27+02:00 debug layer=rpc <- RPCServer.IsMulticlient(rpc2.IsMulticlientIn{})
2022-04-21T15:49:27+02:00 debug layer=rpc -> *rpc2.IsMulticlientOut{"IsMulticlient":false} error: ""
2022-04-21T15:49:27+02:00 debug layer=rpc <- RPCServer.AttachedToExistingProcess(rpc2.AttachedToExistingProcessIn{})
2022-04-21T15:49:27+02:00 debug layer=rpc -> *rpc2.AttachedToExistingProcessOut{"Answer":false} error: ""
2022-04-21T15:49:27+02:00 debug layer=rpc <- RPCServer.FindLocation(rpc2.FindLocationIn{"Scope":{"GoroutineID":-1,"Frame":0,"DeferredCall":0},"Loc":"main.main","IncludeNonExecutableLines":false,"SubstitutePathRules":null})
...
```

### PR DESCRIPTION
**Pull request by aarzilli**
Fixes #2978

### CODE REVIEW

**Comment by aarzilli** [comment]
On hold, being discussed in the issue.

**Comment by derekparker** [comment]
Should this be closed?

**Comment by aarzilli** [comment]
No I think we should merge it, this restores the behavior we had for core files before it was changed by a refactoring.

**Comment by derekparker** [comment]
I'm still a bit confused by this PR. This doesn't change anything about what Recorded returns, just adds a test asserting current behavior.

**Comment by aarzilli** [comment]
The relevant change is the change to the signature of `gdbserver.(*process).Restart` which makes it conform to the `proc.RecordingManipulationInternal` interface. The test is to make sure we don't break it again in the future.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
