### PR TITLE
pkg/terminal: add '-clear' option to 'condition' command

### PR DESCRIPTION
**Pull request by chainhelen**
This change adds the 'clearcond' which will clear condtion on a breakpoint.

### CODE REVIEW

**Comment by aarzilli** [comment]
I don't think this should be a separate command, either a flag to `condition`, like `condition -clear <breakpoint-name-or-id>` or just `condition` without the second argument.

**Comment by chainhelen** [comment]
done

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by aarzilli** [comment]
I must have missed this

**Pull request merged**
