### PR TITLE
service/dap: fix bugs in stdout/stderr handling

### PR DESCRIPTION
**Pull request by hyangah**
Fixes bugs introduced in v1.21.1

* Avoid dropping the last bytes from stderr/stdout when Read returns an error. (Read returns n>0). And skip sending Output event if Read returns n==0.

* Fix the bug that drops all stdout in the existing noDebug mode.

For #3094 #3253 

With this, the vscode-go test passes.
I wish we had testing for non-redirect mode, but I want to get this in soon since these bugs affect vscode go users.

### CODE REVIEW

**Comment by hyangah** [comment]
Looks like teamcity builders had issues for some time. Is this a known problem?

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by aarzilli** [comment]
> Looks like teamcity builders had issues for some time. Is this a known problem?

The builders for ppc and windows/arm64 are offline, the builders for mac/amd64 sometimes die and have to be restarted.

**Review by derekparker — APPROVED** [review]
lgtm

**Pull request merged**
