### PR TITLE
fix: LoadAbstractOriginAndSpecification infinite loop caused by abstr…

### PR DESCRIPTION
**Pull request by zdyj3170101136**
fix https://github.com/go-delve/delve/issues/3766

### CODE REVIEW

**Comment by zdyj3170101136** [comment]
@aarzilli

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by zdyj3170101136** [comment]
> LGTM

could you merge it?

i am waiting for this mr to resolve oom problem.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
