### PR TITLE
fix spelling error

### PR DESCRIPTION
**Pull request by hedenface**
A single word in docs/cli/README

### CODE REVIEW

**Comment by derekparker** [comment]
Here is where the typo should be fixed: https://github.com/go-delve/delve/blob/master/pkg/terminal/command.go#L137

**Comment by derekparker** [comment]
@hedenface will you be updating this PR based off the feedback?

**Comment by hedenface** [comment]
Yes. Lost track, my apologies. I'll get it done soon

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
