### PR TITLE
proc: support reading deferred calls' arguments on linux/arm64

### PR DESCRIPTION
**Pull request by aarzilli**

### CODE REVIEW

**Comment by aarzilli** [comment]
cc @hengwu0

**Comment by hengwu0** [comment]
1、Sorry i forgot this feature is undone.
2、The patch in `EvalScope` is Very well done.
3、I’m dissagreed to add `usesLR` variable in **Arch struct** actually. For Two reason:
&nbsp;&nbsp;&nbsp;&nbsp;a. The `LR` Only exists in arm, this bool variable works like `if Arch.Name=="arm64"`
&nbsp;&nbsp;&nbsp;&nbsp;b. If we continue to add `Architecture independent variables` in `Arch struct` on arm32/mips/ppc with different OS, the `Arch struct` will become more and more complex and huge.

**Comment by aarzilli** [comment]
> The LR Only exists in arm, this bool variable works like if Arch.Name=="arm64"

It also exists on arm (non-64bit version), MIPS (both 32 and 64bit), PowerPC, RISC V, and (according to go source code) s390x.

**Comment by hengwu0** [comment]
> > The LR Only exists in arm, this bool variable works like if Arch.Name=="arm64"
> 
> It also exists on arm (non-64bit version), MIPS (both 32 and 64bit), PowerPC, RISC V, and (according to go source code) s390x.

I know it is called `RA(return address) register` in mips(both 32 and 64bit) and riscv. If you mean LR is RA, the name of `usesLR` may not precise. :)

**Comment by aarzilli** [comment]
> I know it is called RA(return address) register in mips(both 32 and 64bit) and riscv. If you mean LR is RA, the name of usesLR may not precise. :)

It's the name that the runtime uses. PC is called IP on amd64/386

**Comment by hengwu0** [comment]
> It's the name that the runtime uses. PC is called IP on amd64/386

PC called IP on amd64/386 is well known for everyone, and RA called LR may not be popular. How about add an comment here to let mips/riscv developers known?

**Comment by aarzilli** [comment]
> > It's the name that the runtime uses. PC is called IP on amd64/386
> 
> PC called IP on amd64/386 is well known for everyone, and RA called LR may not be popular. How about add an comment here to let mips/riscv developers known?

Done

**Comment by hengwu0** [comment]
Thanks for accepting my suggestion, LGTM.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
