### PR TITLE
TeamCity,goversion: bump test matrix

### PR DESCRIPTION
**Pull request by aarzilli**
Add Go 1.19 to test matrix, drop 1.16.

### CODE REVIEW

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by derekparker** [comment]
Re-running CI.

**Comment by aarzilli** [comment]
CI will always fail because of the bump to the supported version range.

**Comment by derekparker** [comment]
> CI will always fail because of the bump to the supported version range.

Right, it doesn't pick up the new config from the PR branch, shoulda looked closer.

**Pull request merged**
