### PR TITLE
Add support for reverse-{step,stepi,next}

### PR DESCRIPTION
**Pull request by dpapastamos**
This PR contains some bug fixes, improvements and the implementation of some reverse commands.  I have tested this with the rr backend and it seems to work.

### CODE REVIEW

**Comment by aarzilli** [comment]
This doesn't work:

```
% ./dlv --backend rr debug _fixtures/continuetestprog.go
rr: Saving execution to trace directory `/home/a/.rr/__debug_bin-0'.
Hello, World!
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x4aa34f for main.main() ./_fixtures/continuetestprog.go:16
(dlv) c
> main.main() ./_fixtures/continuetestprog.go:16 (hits goroutine(1):1 total:1) (PC: 0x4aa34f)
Current event: 415
    11:	
    12:	func sayhi() {
    13:		fmt.Println("Hello, World!")
    14:	}
    15:	
=>  16:	func main() {
    17:		sleepytime()
    18:		sayhi()
    19:	}
(dlv) clear 1
Breakpoint 1 cleared at 0x4aa34f for main.main() ./_fixtures/continuetestprog.go:16
(dlv) n
> main.main() ./_fixtures/continuetestprog.go:17 (PC: 0x4aa35b)
Current event: 415
    12:	func sayhi() {
    13:		fmt.Println("Hello, World!")
    14:	}
    15:	
    16:	func main() {
=>  17:		sleepytime()
    18:		sayhi()
    19:	}
(dlv) s
> main.sleepytime() ./_fixtures/continuetestprog.go:8 (PC: 0x4aa26f)
Current event: 415
     3:	import (
     4:		"fmt"
     5:		"time"
     6:	)
     7:	
=>   8:	func sleepytime() {
     9:		time.Sleep(time.Millisecond)
    10:	}
    11:	
    12:	func sayhi() {
    13:		fmt.Println("Hello, World!")
(dlv) reverse-step
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x45c190)
Warning: debugging optimized function
Current event: 15
	breakpoint hit during reverseStep, continuing...
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x45c190)
Warning: debugging optimized function
Current event: 15
	breakpoint hit during reverseStep, continuing...
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x45c190)
Warning: debugging optimized function
Current event: 15
	breakpoint hit during reverseStep, continuing...
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x45c190)
Warning: debugging optimized function
Current event: 15
	breakpoint hit during reverseStep, continuing...
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x45c190)
Warning: debugging optimized function
Current event: 15
	breakpoint hit during reverseStep, continuing...
(repeats forever)
```

The problem is that to implement next and step (what about stepout) in reverse you can't just reverse the execution, you also need to place their temp breakpoint on different instructions. This is why they haven't been implemented.

**Comment by dpapastamos** [comment]
> The problem is that to implement next and step (what about stepout) in reverse you can't just reverse the execution, you also need to place their temp breakpoint on different instructions. This is why they haven't been implemented.

I see yes.  I can have a look at that.  Thanks for the review!

**Comment by dpapastamos** [comment]
@aarzilli by the way, do the other patches look ok?  If so I can remove the reverse step/next patches from this PR until I rework and you can merge the other 3 patches?

**Comment by dlsniper** [comment]
@dpapastamos perhaps it would be better to file separate PRs for separate changes to make them easier to review/process/merge.

**Comment by dpapastamos** [comment]
@dlsniper makes sense indeed.  I will close this one for now.

**Pull request closed without merging**
