### PR TITLE
*: Add DeepSource CI config

### PR DESCRIPTION
**Pull request by derekparker**
Adds a config for https://deepsource.io to enable some static analysis CI on this repo.

### CODE REVIEW

**Comment by aarzilli** [comment]
I suspect that this won't work well on the _fixtures directory either, but let's see.

**Comment by sourya** [comment]
> I suspect that this won't work well on the _fixtures directory either, but let's see.

Hi @aarzilli, I maintain the Go analyzer at DeepSource. Can you please give some context about the issue you faced in the analysis of the `_fixtures` directory, so I can look into it and help you?

And thanks to you and @derekparker for creating `delve`. You guys rock!

**Comment by aarzilli** [comment]
_fixtures is a bunch of programs we use to test delve, there's a lot of code that violates normal go coding style (think undocumented exported types, pointers to interfaces, infinite loops...) and at least a couple of program dereference a nil pointer on purpose.

**Comment by sourya** [comment]
If you want to ignore *all* issues raised on files in `_fixtures/` directory, you can add it to the `exclude_patterns` array in the `.deepsource.toml`. I've created a PR for that here: https://github.com/go-delve/delve/pull/1941

If you only want to enable some issues for files inside `_fixtures`, you can add it into `test_patterns`. The PR for that is here: https://github.com/go-delve/delve/pull/1940

To ignore specific issues for test files, I've attached the workflow GIF below:
ignore_test_issues

**Pull request merged**
