### PR TITLE
G struct offset is a pointer to an offset since go1.20

### PR DESCRIPTION
**Pull request by qmuntal**
This PR fixes windows/amd64 port on `gotip`. Since [CL 431775](https://go-review.googlesource.com/c/go/+/431775) the G struct offset is no longer hardcoded to `0x28` but created initialized at runtime and stored in `runtime.tls_g`, just as it is already happening in windows/arm64.

Delve has to account for this change and dereference `runtime.tls_g` in order to obtain the real G struct offset value.

### CODE REVIEW

**Comment by aarzilli** [comment]
I wrote a fix for this yesterday: https://github.com/go-delve/delve/pull/3180/commits/5022c7cccdf46bae8f72a0e3435ba8072d9402f9. It seems to me that the approach is basically the same. In retrospect I should have notified you.

**Comment by qmuntal** [comment]
No problem, I just want to have this fixed, either with your commit or mine. Feel free to submit whichever you prefer.

**Comment by derekparker** [comment]
Hey @qmuntal did you no longer want a review for this code? Was hoping to get this merged soon to fix builds at tip.

**Comment by qmuntal** [comment]
> Hey @qmuntal did you no longer want a review for this code? Was hoping to get this merged soon to fix builds at tip.

Wops, GitHub automatically closed this PR after I unintentionally force-pushed to the PR branch. Fixed.

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
