### PR TITLE
README: rollback gitter chat link.

### LINKED ISSUE #1842: Gitter chat link is dead
The link to gitter chat from readme is a 404

https://gitter.im/go-delve/delve?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

image

### PR DESCRIPTION
**Pull request by chainhelen**
Keep gitter chat link valid.

Fix #1842

### CODE REVIEW

**Comment by derekparker** [comment]
Gitter isn't really used that often, I think we should remove it entirely and possibly replace with a link to the Gophers slack and a plug for the #delve channel. 

@aarzilli thoughts?

**Comment by aarzilli** [comment]
The gophers slack requires making a slack account and being approved by the gophers slack so I wouldn't promote it. But we could remove gitter and just leave the mailing list.

**Comment by derekparker** [comment]
Let's just remove the link.

**Comment by dlsniper** [comment]
As a note, you just need to signup for Slack and confirm the e-mail that you receive from them. As far as we, the Slack admins, are concerned, there's no manual approval process for that part.

**Comment by chainhelen** [comment]
Anyway, remove the link first. Done.

**Pull request merged**
