### PR TITLE
Documentation: watch example for arbitrary address

### LINKED ISSUE #3266: Document using pointer expressions to set watch points on arbitrary memory locations
> 1. What version of Delve are you using (`dlv version`)?

Version: 1.20.1

> 2. What version of Go are you using? (`go version`)?

go version go1.20 darwin/arm64

> 3. What operating system and processor architecture are you using?

macOS 12.6.2 / Apple M1 Max

> 4. What did you do?

Try to set a watch point from the dlv cli on an arbitrary memory addr:

```
(dlv) watch -w 0x14000092408
```

I got this memory addr from manually computing an offset against a register, I don't have a variable name I can reference.

> 5. What did you expect to see?

```
(dlv) watch -w 0x14000092408
Watchpoint 0x14000092408 set at 0x14000092408
```

> 6. What did you see instead?

```
(dlv) watch -w 0x14000092408
Command failed: can not watch "0x14000092408"
```

This is a feature request I guess :)

FWIW, I have a [local patch](https://gist.github.com/felixge/73475181d095135683655898756b4c8e) that seems to work. But I figured I check with y'all before trying to tidy that up for submission.

### PR DESCRIPTION
**Pull request by felixge**
Fixes #3266

### CODE REVIEW

**Review by derekparker — APPROVED** [review]
LGTM

**Review by derekparker — CHANGES_REQUESTED** [review]
Please regenerate the documentation via `go run _scripts/gen-cli-docs.go`.

**Comment by felixge** [comment]
> Please regenerate the documentation via `go run _scripts/gen-cli-docs.go`.

Whups, sorry about that. Done! PTAL.

**Review by aarzilli — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]

**Pull request merged**
