### PR TITLE
pkg/proc: use gore to obtain info from stripped binaries

### PR DESCRIPTION
**Pull request by derekparker**
This patch switches from using a forked version of one of the libraries of goretk/gore to using the module directly. This is possible now that certain functionality has been exposed / fixed within that module making it usable for Delve.

### CODE REVIEW

**Review by aarzilli — DISMISSED** [review]
LGTM

**Review by aarzilli — COMMENTED** [review]
There's a bunch of test failures in TestDebugStripped and TestDebugStripped2, I don't know if you have noticed.

**Comment by derekparker** [comment]
> There's a bunch of test failures in TestDebugStripped and TestDebugStripped2, I don't know if you have noticed.

I'll take a look at them, thanks.

**Review by aarzilli — APPROVED** [review]

**Comment by aarzilli** [comment]
Merged however it currently fails on go1.22

**Comment by adonovan** [comment]
Hi, I came here after reading https://github.com/go-delve/delve/issues/3661, and I wonder whether it was an intended consequence of this PR that delve acquire a AGPL dependency, despite delve itself uses an MIT license.

**Pull request merged**
