### PR TITLE
service/dap/test: add MultiClientCloseServerMock and fix shutdown leak

### PR DESCRIPTION
**Pull request by polinasok**

### CODE REVIEW

**Comment by polinasok** [comment]
@derekparker This is a test only change. I have more things in the pipeline that are based on this. Any chance we can get this in quickly? Thank you.

**Review by aarzilli — APPROVED** [review]

**Comment by aarzilli** [comment]
There's a conflict now that I merged the other PR.

**Comment by derekparker** [comment]
@polinasok if you can rebase and fix the merge conflict we can get this merged asap.

**Comment by polinasok** [comment]
Rebased, test passing

**Pull request merged**
