### PR TITLE
Travis-CI: bump Go version in test matrix

### PR DESCRIPTION
**Pull request by aarzilli**

### CODE REVIEW

**Comment by aarzilli** [comment]
Looks like TestScopesAndVariablesRequest is breaking on Windows/Go1.15. Strange.

**Comment by aarzilli** [comment]
@chainhelen it looks like linux i386 is failing with Go 1.15.

**Comment by chainhelen** [comment]
I will check.

**Comment by briandealwis** [comment]
This change wasn't noted in the release notes.  It seems a rather important change for a micro release.

**Pull request merged**
