### PR TITLE
service/dap: handle no-such-process disconnect error

### PR DESCRIPTION
**Pull request by polinasok**

### CODE REVIEW

**Comment by aarzilli** [comment]
I was thinking about this during the weekend and I think I know what's going on with that test. I want to take a deeper look at it, probably later this week or during the weekend.

**Comment by polinasok** [comment]
> I was thinking about this during the weekend and I think I know what's going on with that test. I want to take a deeper look at it, probably later this week or during the weekend.

I am intrigued. Looking forward to the mystery reveal :)

**Comment by polinasok** [comment]
I will update this PR once #2477 is in.

**Comment by derekparker** [comment]
@polinasok #2477 has been merged.

**Comment by polinasok** [comment]
TestAttachStopOnEntry is no longer flaky, so I have dropped the changes in the test.
Keeping the no-such-process handling changes. Except I am no longer sure how to trigger such a case in the tests.

**Review by aarzilli — APPROVED** [review]

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
