### PR TITLE
go.mod: require go-delve/liner instead of peterh/liner

### PR DESCRIPTION
**Pull request by hyangah**
Use of `replace` in go.mod breaks delve installation using
`go install`. (see https://github.com/golang/go/issues/40276)
Workaround this limitation by explicitly require the fork
github.com/go-delve/liner.

go-delve/liner@v1.2.2-1 already has go.mod module name fixed
to be github.com/go-delve/liner. go-delve/liner@v1.2.2-1 also
has complete go.mod that made github.com/mattn/go-runewidth
declared as an implicit dependency and get pulled into the vendor
directory correctly.
 
Fixes go-delve/delve#2904

### CODE REVIEW

**Review by aarzilli — APPROVED** [review]

**Comment by hyangah** [comment]
cc @derekparker

**Comment by aarzilli** [comment]
Is vscode-go still installing `@master`?

**Comment by hyangah** [comment]
Not any more, but some systems depending on github/vscode dev containers still install dlv from master. Fixes in github&vscode were committed, but not released. So some users in downstream are stuck. :-(

**Comment by hyangah** [comment]
Thanks a lot!

**Comment by chattarajoy** [comment]
please make changes to the name of module in the fork, this is causing issues when downloading the latest version:

image

**Pull request merged**
