### PR TITLE
service/dap: special-handle build errors to avoid error dialogue in vscode

### PR DESCRIPTION
**Pull request by polinasok**
**Before**
image
```
2021-07-22T23:17:28-07:00 debug layer=dap debug layer=dap building binary '/Users/polina/delve/__debug_bin' from '/Users/polina/go/src/temp.go' with flags ''
2021-07-22T23:17:29-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"Build Error: go build -o /Users/polina/delve/__debug_bin -gcflags all=-N -l /Users/polina/go/src/temp.go\n# command-line-arguments\n../go/src/temp.go:116:9: syntax error: unexpected ) at end of statement (exit status 2)\n","source":{}}}
2021-07-22T23:17:29-07:00 debug layer=dap Failed to launch: Build error: Check the debug console for details.
2021-07-22T23:17:29-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":false,"command":"launch","message":"Failed to launch","body":{"error":{"id":3000,"format":"Failed to launch: Build error: Check the debug console for details."}}}
2021-07-22T23:17:29-07:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"disconnect","arguments":{}}
2021-07-22T23:17:29-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"disconnect"}
2021-07-22T23:17:29-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2021-07-22T23:17:29-07:00 debug layer=dap DAP server stopping...
2021-07-22T23:17:29-07:00 debug layer=dap DAP server stopped
```
**After**
image
```
2021-07-22T23:18:37-07:00 debug layer=dap building binary '/Users/polina/delve/__debug_bin' from '/Users/polina/go/src/temp.go' with flags ''
2021-07-22T23:18:38-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"Build Error: go build -o /Users/polina/delve/__debug_bin -gcflags all=-N -l /Users/polina/go/src/temp.go\n# command-line-arguments\n../go/src/temp.go:116:9: syntax error: unexpected ) at end of statement (exit status 2)\n","source":{}}}
2021-07-22T23:18:38-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2021-07-22T23:18:38-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
2021-07-22T23:18:38-07:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"disconnect","arguments":{}}
2021-07-22T23:18:38-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"disconnect"}
2021-07-22T23:18:38-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2021-07-22T23:18:38-07:00 debug layer=dap DAP server stopping...
2021-07-22T23:18:38-07:00 debug layer=dap DAP server stopped

```

Updates golang/vscode-go#1375

### CODE REVIEW

**Comment by polinasok** [comment]
@suzmue @hyangah

**Comment by polinasok** [comment]
@mfussenegger would this change be an issue for nvim?

**Comment by mfussenegger** [comment]
> @mfussenegger would this change be an issue for nvim?

Yes currently it would. Thanks for asking.

`nvim-dap` clears the console output if a new session is started. With this change it would first write the error message to the console, and then after it receives the `launch` response it would immediately clear it. So for users the error message won't be visible.
I could try to refine the reset logic and account for messages that are received between the launch request and the response.

**Comment by polinasok** [comment]
> > @mfussenegger would this change be an issue for nvim?
> 
> Yes currently it would. Thanks for asking.
> 
> `nvim-dap` clears the console output if a new session is started. With this change it would first write the error message to the console, and then after it receives the `launch` response it would immediately clear it. So for users the error message won't be visible.
> 
> But I could try to refine the reset logic and account for messages that are received between the launch request and the response.

I can also add a launch attribute to enable/disable this new feature. Then you can leave things as-is.

**Comment by polinasok** [comment]
@hyangah I am having second thoughts about this change because it is so vscode specific. I was thinking we could avoid impact on other clients with a hidden launch configuration attribute to be set by the vscode-go extension, but that seems to be too vscode-specific as well. What if instead with catch the launch error in the thin adapter in vscode-go repo and replace it with terminated event and launch success instead?

**Comment by polinasok** [comment]
We are working with vscode devs to honor `showUser=false` and suppress the pop-up that way, so we won't need this hack or the equivalent on the extension side. Closing.

**Pull request closed without merging**
