### PR TITLE
Add mac/amd64 & linux/arm64 builders

### PR DESCRIPTION
**Pull request by nd**

### CODE REVIEW

**Review by aarzilli — APPROVED** [review]
LGTM. Does this fix the error we've been seeing recently (`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`)?

**Comment by nd** [comment]
Yes it should fix it. We added a linux/arm64 machine and linux/amd64 build was scheduled there. BTW you can add linux/arm64 to the matrix, or I can add it if you tell me the go version you want to test.

**Comment by aarzilli** [comment]
> Yes it should fix it. We added a linux/arm64 machine and linux/amd64 build was scheduled there. BTW you can add linux/arm64 to the matrix, or I can add it if you tell me the go version you want to test.

That's great. Thank you. `linux/arm64/1.16`.

**Comment by derekparker** [comment]
LGTM - however I'm also seeing `Number of tests 0 is 1 less than the provided threshold 1; exit code 1 (Step: Test (Docker))` faillures in the CI now.

**Comment by nd** [comment]
> faillures in the CI

they happens due to missing build requirement: linux/amd64 build runs on linux/arm64 machine and fails.

**Comment by derekparker** [comment]
@nd can you please rebase this and fix the conflicts?

**Comment by nd** [comment]
rebased

**Comment by aarzilli** [comment]
Looks like there still are problems, on 386: `WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested` and on linux/arm64 `pull access denied for arm64/ubuntu, repository does not exist or may require 'docker login':`

**Comment by nd** [comment]
Sorry, fixed the docker image name: in #2355

**Pull request merged**
