### PR TITLE
Fix broken link to JSON-RPC

### PR DESCRIPTION
**Pull request by becheran**
Remove list of implementation since it seems no longer maintained

### CODE REVIEW

**Comment by aarzilli** [comment]
Given that it's version 1 it should be https://www.jsonrpc.org/specification_v1

**Comment by becheran** [comment]
@aarzilli sure. Changed it in PR

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by aarzilli** [comment]
Thank you.

**Pull request merged**
